### ISSUE TITLE
Uncaught TypeError: Converting circular structure

### ISSUE THREAD

**Issue by anusurendra** [vkiryukhin/jsonfn#19]
@vkiryukhin,

I am using jsonfn to stringfy a D3 object. However, I get a `Uncaught TypeError: Converting circular structure` error. Below is the code: 

 ```
 d3.json("model_files/e_coli_core.json", function(error, data) {
     if (error) console.warn(error);
     var options = {menu: 'all', canvas_size_and_loc: { x: '200', y: '200', width: '5000', height: '5000' }};
     var b = escher.Builder(null, data, null, d3.select('#model_container'), options);
     console.log(b);
     **localStorage.setItem('b', JSONfn.stringify(b));**
 });
```

Any help would be appreciated.

**Comment by vkiryukhin** [comment]
Technically speaking, jsonfn cannot stringify any objects which  directly manipulate the DOM  or use some default methods and properties of the Window object. Another restriction: properties or methods of the object should not refer to the object itself. In both cases you will get "circular structure" error. Consider following rule: if JSON.stringify(yourObject) works for you, jsonfn also should work and vise versa.

Hope this helps,
--Vadim
